### ISSUE TITLE
#M11. Display Hackathon details

### ISSUE THREAD

**Issue by stefdworschak** [Code-Institute-Community/ci-hackathon-app#107]
Create a new page to display the detailed information about a hackathon when clicking on the "Read More" link on the "View Hackathons" page.

**Comment by auxfuse** [comment]
@auxfuse 👋 I'll take this @stefdworschak and give it a whirl.

**Comment by stefdworschak** [comment]
Thanks, @auxfuse! I just assigned it to you.

**Comment by auxfuse** [comment]
https://github.com/Code-Institute-Community/ci-hackathon-app/pull/119 <--- PR added for this.

**Comment by auxfuse** [comment]
Please consider closing this as this has already been fulfilled in part by another PR. I've closed my subsequent PR and unassigned myself from this in case you want to keep it open for the unfulfilled works to be carried out by another.

**Comment by TravelTimN** [comment]
@stefdworschak 
The work on this PR #119  looked really great, apart from the suggested layout (sticking with basic wireframes, but open to adjustments).
Honestly, looks like a significant amount of extra work versus the other PR that was merged.

Not urgently immediate, but I'd be happy to try and get #119 active again, @auxfuse  if you're game (no priority).
