### ISSUE TITLE
#P15. As Participant, I want to see a list of hackathons I have participated in.

### ISSUE THREAD

**Issue by stefdworschak** [Code-Institute-Community/ci-hackathon-app#154]

**Comment by TravelTimN** [comment]
👍🏻 
I came here to add this as a suggestion, and noticed #154 already exists here.

However:
As Participant, I want to see a list of hackathons I have participated* in

(participated, not enrolled)

**Comment by stefdworschak** [comment]
Change approved :laughing:

**Comment by stefdworschak** [comment]
Actually this is a duplicate of #P14
