### ISSUE TITLE
#M00. As a User, I would like to register an account.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#18]
Registration should include the following details:
- First Name
- Last Name
- Email Address
- Password
- Slack Display Name
- Current Module on LMS
  - dropdown options
  - includes option for alumni
- Registration Code
  - provided by CI
  - changes with each Hackathon

**Comment by auxfuse** [comment]
@auxfuse

**Comment by TravelTimN** [comment]
🧡🤜 Wonderful, thanks @auxfuse! I've moved it over to **_In Progress_** now.
Quick note: I'm about to do a Workshop demo that has the base/core setup done, so you'll want to pull down those changes in about an hour after my demo call.

**Comment by auxfuse** [comment]
I can try incorporate the majority of what John Traas raised in the call? Something around a boolean of staff or otherwise to the registration that can then be approved in the admin panel?

**Comment by TravelTimN** [comment]
Sounds perfect @auxfuse! I've closed down the other User Stories as "similar" to this, since you've come up with a brilliant solution around this issue! 👍

**Comment by auxfuse** [comment]
@TravelTimN I know you are mega busy with all of this, but can we ammend the title of this issue to `As User` <-- as this will then incorporate all types of users and then change the prefix to "M" for Miscellanous please? :D

**Comment by TravelTimN** [comment]
Done and done! 👍 for that - it's now #M00
**_#M00. As a User, I would like to register an account. #18_**

**Comment by auxfuse** [comment]
@TravelTimN This can be closed now:

See PRs:

- https://github.com/Code-Institute-Community/ci-hackathon-app/pull/83
- https://github.com/Code-Institute-Community/ci-hackathon-app/pull/89
