### ISSUE TITLE
#M21. Add functionality to set maximum number of registrations.

### ISSUE THREAD

**Issue by stefdworschak** [Code-Institute-Community/ci-hackathon-app#197]

**Comment by TravelTimN** [comment]
Intriguing! A maximum number of registrants... 🤔 
I suppose in some instances it makes sense, would like to keep it as "unset" for most though, presumably?

**Comment by stefdworschak** [comment]
Yep exactly. It seems that with the upcoming ("secret" until we announce it) hackathon, this is wanted.
