### ISSUE TITLE
#P03. As Participant, I would like to update my profile.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#20]
Editable profile details should include:
- First Name
- Last Name
- Email Address
- Slack Display Name
- Current Module on LMS
  - dropdown options
  - includes option for alumni
- Shipping Address
  - hidden by default
  - is enabled only if part of a winning team

**Comment by natalijabujevic0708** [comment]
@natalijabujevic0708

**Comment by TravelTimN** [comment]
Thanks @natalijabujevic0708! You might want to check with @auxfuse who is working on some User Auth for #18 - as this will correlate with that once finished.

**Comment by auxfuse** [comment]
I am hoping top have all the user auth stuff done by this weekend @natalijabujevic0708 Once done I'll ping you in this thread to let you know that the project can be then cloned for your own issue participation 😄

**Comment by natalijabujevic0708** [comment]
@auxfuse perfect, thanks :)

**Comment by auxfuse** [comment]
@natalijabujevic0708 My issue is now done, you should be able to just git pull upstream master to get the lastest code base and then take it from there 😀

See PRs:

#83
#89
