### ISSUE TITLE
#P04. As Participant, I would like to see a list of any upcoming Hackathons.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#21]

**Comment by Ri-Dearg** [comment]
@Ri-Dearg

**Comment by Ri-Dearg** [comment]
@Ri-Dearg

**Comment by TravelTimN** [comment]
Thanks @Ri-Dearg ! Can't wait to see your PR on this user story!

**Comment by TravelTimN** [comment]
@Ri-Dearg 
Quick note: I'm doing the demo on the call tomorrow morning which will include the bulk of the main setup, base template, static file setup, etc. - you'll want to make sure to pull those changes after they've been merged tomorrow after the workshop demo.

**Comment by Ri-Dearg** [comment]
@TravelTimN
Perfect, will do! Thanks a bunch for heading this, very excited for it!
