### ISSUE TITLE
#P09. As Participant, I would like to submit our Hackathon entry.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#26]
Submissions should include:
- Team Name
- Name of Team Speaker during presentations
- Link to Source Code / Repository
- Link to Deployed Site
- Consent option to share deployed site on CI social media

**Comment by ClaireLally8** [comment]
Gimmee this one! @clairelally8 :D

**Comment by Eventyret** [comment]
@TravelTimN @ClaireLally8 Would it not be nice to be able to upload images or a screenshot etc as well? That way it could be displayed or automated down the line for Social Media posts etc? (I mean it would mean add an image field)

**Comment by TravelTimN** [comment]
Yep! There was discussions about this, but we're not sure (yet) fully on this. It would therefore involve the use of AWS S3 for image upload, for example (or similar). It's an idea on the backburner for later at this stage.

**Comment by ClaireLally8** [comment]
@Eventyret @TravelTimN I've technically finished this, so I ain't doing anymore.  ;)  *crosses arms & sulks*
