### ISSUE TITLE
#S03. As Staff, I would like to update my profile.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#32]
- Editable profile details should include:
  - First Name
  - Last Name
  - Email Address
  - Slack Display Name

**Comment by lesreddy** [comment]
@lesreddy

**Comment by stephyraju** [comment]
@stephy

**Comment by stephyraju** [comment]
@stephy

**Comment by TravelTimN** [comment]
Thanks @lesreddy !
You might check with @auxfuse on #20 , working with @natalijabujevic0708 on quite similar for Particpants. Might actually just be able to combine this into a single Update method, similar to the Creation of accounts.

**Comment by lesreddy** [comment]
Thanks @TravelTimN I will chat to @auxfuse and @natalijabujevic0708, I think you are right it is pretty much one and the same.

**Comment by auxfuse** [comment]
Hi @lesreddy  just touching base with you 😄

I am hoping to have all the user auth stuff done by this weekend. Once done I'll ping you in this thread to let you know that the project can be then forked for your own issue participation 😄

**Comment by lesreddy** [comment]
Hi @auxfuse thanks for touching base, thats sounds great, I will go on from there with @natalijabujevic0708

**Comment by auxfuse** [comment]
@lesreddy My issue is now done, you should be able to just `git pull upstream master` to get the lastest code base and then take it from there 😀

See PRs:

- #83
- #89

**Comment by lesreddy** [comment]
Thats great thanks @auxfuse, congrats on all the great work you have put in, I will touch base with @natalijabujevic0708 and see what we can come up with

**Comment by lesreddy** [comment]
Hey @TravelTimN after extensive brainstorming, analysis and research I have no idea how to resolve this issue! 😀 I wont hold it up any longer, if you want to put it back into to do I will grab some popcorn and watch from the sidelines and observe how someone with greater django skills can resolve, I might jump into something else thats less confusing for me, maybe some template styling or something!
