### ISSUE TITLE
#S04. As Staff, I would like to see a list of any upcoming Hackathons.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#33]

**Comment by Ri-Dearg** [comment]
@Ri-Dearg Heya, I'm wondering if this is different from #P04 #21 "As a Participant, I would like to see a list of upcoming Hackathons." As in, maybe the visibility isn't public, or that there are different ones displayed for each group?

Let me know! I'll get to work on it, as I already have a draft for #21 finished.

**Comment by stefdworschak** [comment]
@Ri-Dearg it's a good question. I guess we might want to add a status to the Hackathon model for a status and then allow for drafts and maybe non-public hackathons which are both only displayed for staff and/or only admins. What do you think @TravelTimN?

**Comment by TravelTimN** [comment]
@Ri-Dearg good catch - there ended up being some duplicates it seems, like with registering an account, profile pages, and this. (my fault, sorry).
@stefdworschak - hmm could be something to look into? I know we do have some non-public Hackathons like with ETBs, so could be worth investigating!

**Comment by Ri-Dearg** [comment]
In any case, I think it would be easy to add some template logic and/or a filter for staff to the current Hackathon list Then it'll display the extra events on the page. If you decide anything, you can tag me here and I'll be happy to take it on! 😄

**Comment by stefdworschak** [comment]
@TravelTimN closing this and creating separate issues for 1) drafts 2) private/organization specific Hackathons.
