### ISSUE TITLE
#S07. As Staff, I would like to view all teams' information.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#36]
- Visible items should only include:
  - Team Name
  - Slack Display Names of Members

**Comment by stephyraju** [comment]
@stephy

**Comment by TravelTimN** [comment]
Thanks @stephyraju ! I've moved to **_In Progress_**!

**Comment by stephyraju** [comment]
Thanks!

**Comment by AMcCall22** [comment]
Hi @stephyraju , I have put my name against #P07, As a participant, I would like to view my team's info. Thinking these 2 issues are pretty similar, wondering if we should join forces? Will PM you on slack :)

**Comment by TravelTimN** [comment]
You're right, @AMcCall22 - they should've been one in the same - I like the collaboration teamwork! ❤️

**Comment by TravelTimN** [comment]
@stephyraju 
I'm just checking-in with this issue, since it's still "Open".
How are you and @AMcCall22  getting on with progress, or has this been sorted via a different PR now?

**Comment by stephyraju** [comment]
@TravelTimN 
I'm still working on to solve this. Ali has started and already done some of the backend work, and now I'm checking with the remaining some issues. It's not completed yet. The template is almost done. The team members and hackathone name are appearing. Now working on with the authentication part.
I have a silly question on this, What is the difference between the" view all Team information " to Staff and Participant?
