### ISSUE TITLE
#S08. As Staff, I would like to Judge each submission.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#37]
- Becomes available only after a Hackathon End Date/Time
- Judging per team using the standard criteria:
  - Presentation and Adherence to Theme (1-15 dropdown score)
  - Team Collaboration (1-15 dropdown score)
  - Usability and Practicality (1-10 dropdown score)
  - Effective User of Course Knowledge (1-10 dropdown score)
  - Awesomeness (1-10 dropdown score)
- Cannot edit scores once submitted

**Comment by Sarosim** [comment]
@Sarosim

**Comment by TravelTimN** [comment]
Thanks @Sarosim !

**Comment by Sarosim** [comment]
@TravelTimN I'd add one more field to the HackProjectScoreCategory model, to store the score range (some are 1-10, some 1-15) so it can be read from the model and doesn't have to be hard coded in the functions. I'd call it `top_score` or `best_score` so we know the range is from 1 up to this. What do you think?
![image](https://user-images.githubusercontent.com/44575078/96354400-1c5b8780-10ce-11eb-97d8-5abff338ee36.png)

**Comment by stefdworschak** [comment]
@Sarosim as mentioned in my comment from the PR I would suggest using `max_score` as this is a very common convention. As for a `min_score` yes you can add it, but I would default it to 1 as well as I don't think we'll much need to use it.

**Comment by Sarosim** [comment]
Are we okay with using the admin panel for adding Project Score Categories, as only admins will add them anyway, or do we want to build this functionality within the hackathon app's judging features?

**Comment by Sarosim** [comment]
@stefdworschak the whole issue itself is not fully resolved, it was just a connected fix, as the model was missing those fields, I'm working on the judging page still

**Comment by stefdworschak** [comment]
@Sarosim are you working on the overall issue or should I move this back to be picked up?

**Comment by Sarosim** [comment]
I am @stefdworschak, close to have it built, then needs testing and refactoring. I have hardly a minute for it in the next two days, so will try to get to PR over the weekend.
