### ISSUE TITLE
#A02. As Admin, I would like to create new Hackathon events.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#40]
- Hackathon Name
- Hackathon Start Date/Time
- Hackathon End Date/Time
- Hackathon Theme
- Hackathon Description
- Org
- Status

**Comment by hebs87** [comment]
@hebs87

**Comment by TravelTimN** [comment]
Thanks @hebs87! I'll move this to In Progress on the Projects board!
Quick note: I'm doing the demo on the call tomorrow morning which will include the bulk of the main setup, base template, static file setup, etc. - you'll want to make sure to pull those changes after they've been merged tomorrow after the workshop demo.

**Comment by hebs87** [comment]
Perfect, cheers @TravelTimN! I'll be in work so I may not be able to make the call tomorrow morning, but I'll make sure to pull the changes in before getting started.

**Comment by TravelTimN** [comment]
@hebs87  - actually, would you be interested in #41 and #42 ? They are the additional CRUD functionality for what you're working on. (#41 - Edit an Event // #42 - Delete an Event)
Let me know, and happy to assign to you there, also.

**Comment by hebs87** [comment]
@TravelTimN Sure, go ahead and assign those to me too please.

**Comment by TravelTimN** [comment]
Thanks Sunny!
