### ISSUE TITLE
#A05. As Admin, I would like to manually trigger an event that divides teams/judges evenly.

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#43]
- Once an admin triggers the event to distribute teams/judges:
    - Number of teams and participants per team should depend on total number of participants.
    - This should assign a random Judge/Mentor to each team as well.
    - To ensure a balanced range of skill levels in each team, the distribution algorithm should assign participants to teams based on their experience (LMS Module) ie. divvy out all Alumni first (if any), then MS4, MS3, MS2, MS1.
    - The aim is to have between 4-7 participants per team ideally.

**Comment by Sarosim** [comment]
Is this user story practically to automatically trigger #M02 (#48)?  So the Admin will be able to provide the triggering condition (either exact date/time or  X-hours/days prior to event start date/time) and the teams and judges split will be performed.  We'll need to define the desired output, is it to notify the Admin(s) or display on the page right away?

**Comment by TravelTimN** [comment]
@Sarosim - yes that's correct! This one (#A05) is more for the "manual" trigger of team distribution.
#48 (#M02) is an ideal/desired outcome, where this would all be done automatically, without needing the Admin to trigger this event manually.

**Comment by TravelTimN** [comment]
Apologies on the confusion.
Step 1: get it working to distribute teams, based on a manual event that gets triggered by an Admin user.
Step 2: #48 is worded poorly (sorry), but that would become the "automated" method, so these events are auto-triggered without Admin interaction, something like 48hrs prior to the start date/time of the Hackathon itself.
I'll update both accordingly to hopefully clarify these, thanks!

**Comment by TravelTimN** [comment]
This also relates to #23 as well, for whomever decides they'd like to tackle this issue.

**Comment by stefdworschak** [comment]
@tdunn891 no pressure, but just wanted to see how you're getting on on this issue? :)

**Comment by TravelTimN** [comment]
@tdunn891 
Hey, I'm just checking-in on this issue, as it's still "Open".
How're you getting on there?
Anything we might be able to help out with to progress, or shall we 'release' this back for someone else to pick-up now?

**Comment by tdunn891** [comment]
Apologies guys. Yes, please release. Thanks.
