### ISSUE TITLE
#M01. Judging Automation

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#47]
- Once all Judges have submitted their scores, an automatic tally of scores should determine the winning team.
- This should also trigger the winning team's profile to allow them to update their shipping address.

**Comment by natalijabujevic0708** [comment]
@natalijabujevic0708

**Comment by stefdworschak** [comment]
HI @natalijabujevic0708, assigned to you and moved to "In Progress".
