### ISSUE TITLE
#T01 Footer Content & Styling

### ISSUE THREAD

**Issue by JimLynx** [Code-Institute-Community/ci-hackathon-app#53]
@JimLynx

**Comment by TravelTimN** [comment]
Thanks @JimLynx ! Can't wait to see what you contribute!

**Comment by alexeykuz-sys** [comment]
@alexeykuz-sys

**Comment by TravelTimN** [comment]
@alexeykuz-sys - I can see you've tagged yourself here. Will you be contributing to this in partnership with @JimLynx above, or are you looking at doing something separate?

**Comment by alexeykuz-sys** [comment]
I would like to work on separate issue. I'd prefer to do landing page?

**Comment by TravelTimN** [comment]
@JimLynx modified to #T01 --- T will be for Templates since we have a few people wanting to do various template changes.
