### ISSUE TITLE
#M05 Creating Hackathon Database Models

### ISSUE THREAD

**Issue by Ri-Dearg** [Code-Institute-Community/ci-hackathon-app#61]
Database Models to be created:
- HackAwardCategory
- Hackathon
- HackTeam
- HackProject
- HackProjectScore
- HackProjectScoreCategory

Model Schema can be found on the [Development Wiki](https://github.com/Code-Institute-Community/ci-hackathon-app/wiki/Development)

@Ri-Dearg

**Comment by TravelTimN** [comment]
Thanks @Ri-Dearg

**Comment by TravelTimN** [comment]
Closing - PR merged successfully 🎉
