### ISSUE TITLE
#M06 As a User, I would like to view my Profile Page

### ISSUE THREAD

**Issue by Jays-T** [Code-Institute-Community/ci-hackathon-app#67]
Participants should have the ability to access their personal profile page once they've successfully registered and logged in.

**Comment by TravelTimN** [comment]
Thanks @Jays-T - I understand what you mean here, but this would be a halfway point between #18 and #20  ... you might check in with @auxfuse in relation to how the setup is being done, does it auto redirect to the user's profile upon registering by default?

**Comment by Jays-T** [comment]
Ah, and I also tagged the issue incorrectly I believe.. I'll communicate with @auxfuse about this @TravelTimN

**Comment by Jays-T** [comment]
@TravelTimN I'd like to handle the creation and structure of the profile page.

**Comment by TravelTimN** [comment]
@Jays-T actually, you might discuss with @aticodein, who has submitted a PR for viewing the profile already on #69

**Comment by auxfuse** [comment]
Hi @Jays-T just touching base with you 😄

I am hoping to have all the user auth stuff done by this weekend. Once done I'll ping you in this thread to let you know that the project can be then forked for your own issue participation 😄

@TravelTimN I'll add my PR tomorrow night all going well and will let all dependent on that know too 😉
