### ISSUE TITLE
#M07 As a developer, I would like an easy way to automate the repo and Virtual Environment setup on a local IDE

### ISSUE THREAD

**Issue by JimLynx** [Code-Institute-Community/ci-hackathon-app#70]
As a developer, the environmental setup on a local IDE is not as straightforward as first anticipated. 

In my case, I:

- Opened VSCode

- Cloned the forked repository

- Created the .env file

- Ran the` python -m venv .venv` command, and although the `.venv` folder was created, virtual environment was not initialised

Resolve:
A way to automate this process with all of the correct commands in sequence would be excellent.

@eventyret

**Comment by Eventyret** [comment]
Sure ill create up some scripts.

**Comment by Eventyret** [comment]
Or is now created for you @JimLynx

**Comment by TravelTimN** [comment]
Thanks @Eventyret! Pending request on there from Stefan, before it can be merged.

@JimLynx I've updated the Issue to "_As a developer_", as this relates to the development side, not the actual app users for user stories. 😉 

This Issue will auto-close now, once #71 is adjusted and merged.

**Comment by Eventyret** [comment]
> Thanks @Eventyret! Pending request on there from Stefan, before it can be merged.
> 
> @JimLynx I've updated the Issue to "_As a developer_", as this relates to the development side, not the actual app users for user stories. 😉 
> 
> This Issue will auto-close now, once #71 is adjusted and merged.

I'll merge it in as update to this one.
Could we mark it had hacktoberfest please?

**Comment by stefdworschak** [comment]
@Eventyret I just added a small comment. Could you have a look? Overall it's good to go.

**Comment by TravelTimN** [comment]
@Eventyret Yep! Will mark it as Hacktoberfest-Approved once it's fully merged 👍
