### ISSUE TITLE
#B01 Minor issue with setup.bat script .env info

### ISSUE THREAD

**Issue by JimLynx** [Code-Institute-Community/ci-hackathon-app#75]
@JimLynx
After running setup.bat, the script injects SITE_NAME as "localhost", which does not run on local IDE

**Comment by TravelTimN** [comment]
@JimLynx 
Great catch! If you're happy to fix that, then please open the PR for this one! 👍

**Comment by TravelTimN** [comment]
All merged - closing Issue - thanks @JimLynx !

**Comment by Eventyret** [comment]
Thanks for fixing that plesky one @JimLynx ❤️
