### ISSUE TITLE
#M08 - Build test data for development

### ISSUE THREAD

**Issue by TravelTimN** [Code-Institute-Community/ci-hackathon-app#84]
To help with development, it would be great to have a bunch of test data.
This would allow developers to `loaddata` or fixtures from a JSON file perhaps.
It could contain a bunch of sample users and hackathon events.

It should be possible to generate them from the admin panel initially, and then perform a `dumpdata` command to generate them into a JSON file.

For example, let's assume you have created some test users (of various types - staff, admin, participants, etc), and some sample hackathon events. You therefore should be able to `dumpdata` as such:

`python3 manage.py dumpdata profiles > profiles.json`
and
`python3 manage.py dumpdata hackathon > hackathon.json`

In theory, this would generate the data from the admin panel, directly into the JSON file, so any other developer/contributor can simply `loaddata` and have some sample data already loaded.

Further information from the Django Docs:
https://docs.djangoproject.com/en/3.1/ref/django-admin/#dumpdata

**Comment by andrewdempsey2018** [comment]
@andrewdempsey2018 I did a few tests and think I can handle this task.

**Comment by Sarosim** [comment]
@Sarosim I can do this,

**Comment by Sarosim** [comment]
@TravelTimN @stefdworschak  I guess there are some changes planned in the models or pending in pull requests (there is one minor change to the models in my other pull request S08 or an open issue #101 M10), it means anytime we update the models, these will need to be updated as well, right?

**Comment by stefdworschak** [comment]
@Sarosim yes, that's true. So whoever is changing the model should probably update the test data as well or at least test if the current data still works with the changed models.

**Comment by TravelTimN** [comment]
Closing issue, as it's been handled via #104 and #111
