### ISSUE TITLE
#M09 Profile Page Design

### ISSUE THREAD

**Issue by Jays-T** [Code-Institute-Community/ci-hackathon-app#88]
I would like to be assigned to the design of the user profile page/area.

**Comment by Eventyret** [comment]
If this is an existing issue @Jays-T you can make a comment on that issue itself and tag your own name on it 👍

**Comment by Jays-T** [comment]
As far as I can tell, there isn't one open yet on this issue @Eventyret.

**Comment by TravelTimN** [comment]
@Jays-T just a quick question:
Is this related to purely "styling" of the profile page?
#67 was done already, might be related there?

**Comment by Jays-T** [comment]
@TravelTimN currently purely styling since much of the backend has yet to be added. I guess I missed #67, or it may have already been marked as closed.
