### ISSUE TITLE
#M10. Update Hackathon and Profile model with new fields.

### ISSUE THREAD

**Issue by stefdworschak** [Code-Institute-Community/ci-hackathon-app#91]
Hackathon: 
    - org (default: CodeInstitute)
    - status (draft/published/deleted; default: draft)

User:
   - org (default: CodeInstitute)

**Comment by auxfuse** [comment]
@auxfuse I'll take this one too. Do we have a proposed list of organisations? Or, will this just be a CharField with a default value of CI?

**Comment by auxfuse** [comment]
@stefdworschak @TravelTimN Can this issue be closed please so that we get it off the _in progress_ list 😀🤜
