### ISSUE TITLE
#P04.2. Only display Hackathons where the org is CodeInstitute or where the `user.org == hackathon.org`

### ISSUE THREAD

**Issue by stefdworschak** [Code-Institute-Community/ci-hackathon-app#93]
Depends on [#M10. Update Hackathon and Profile model with new fields.](https://github.com/Code-Institute-Community/ci-hackathon-app/issues/91)

This applies for user_type staff as well.

**Comment by natalijabujevic0708** [comment]
@natalijabujevic0708
