### ISSUE TITLE
#T04 Update all_auth templates

### ISSUE THREAD

**Issue by stefdworschak** [Code-Institute-Community/ci-hackathon-app#94]
![image](https://user-images.githubusercontent.com/31205982/96756763-70b37f80-13cc-11eb-9fec-9a66e7273561.png)

This is an issue for multiple PRs.

Please tag yourself and say which templates you will be working on!

**Comment by auxfuse** [comment]
Hi @stefdworschak is the general flow of each template to follow that of the login/signup wireframes where the content is on the left, and the CI Hackathon Logo on the right? See below screenshot as example:

![image](https://user-images.githubusercontent.com/48055438/96794288-d6683180-13f5-11eb-9ffe-6f6c593a21a3.png)

If so, I will take them all and run through them in one fell swoop following along with the general wireframe theming based on Registration/Login wireframes.

**Comment by stefdworschak** [comment]
@auxfuse I think this is mainly for the register and login, but I would ask @TravelTimN maybe?

**Comment by Jays-T** [comment]
@stefdworschak I'm taking over this issue from @auxfuse so feel free to assign it to me. :)

**Comment by auxfuse** [comment]
Thanks @Jays-T 🤜

**Comment by TravelTimN** [comment]
Closing issue. PR #118
