### ISSUE TITLE
#T05 Style Register & Login Forms

### ISSUE THREAD

**Issue by JimLynx** [Code-Institute-Community/ci-hackathon-app#96]
@JimLynx 

Register & Login Forms require styling 

## Expected Behavior

Styling to keep consistent with the current UX

## Current Behavior

Forms are squished to the left and rather unsightly

## Possible Solution

CSS 🥇 

![image](https://user-images.githubusercontent.com/65254741/96835125-0d146b00-143b-11eb-990a-78c9a440b02f.png)
![image](https://user-images.githubusercontent.com/65254741/96835058-f110c980-143a-11eb-9cbc-af54f6577d38.png)

**Comment by auxfuse** [comment]
Hi @JimLynx there is an issue already open for these:

if you want to take these that is no hassle, there are wireframes available and the default styling of these should look like those:

See [here](https://github.com/Code-Institute-Community/ci-hackathon-app/issues/94) for more details on the full list of templates needing attention.
